//! Real-data checks for the Mod Organizer 2 import (MASTER_SPEC §26.10), against the user's own
//! setup at `D:\Skyrim-MO2-Salvage\MO2`. They only read it: nothing is stored, nothing is created,
//! and the setup's settings and profile files are hashed before and after to prove it.
//!
//! These are `#[ignore]`d because they need that machine's setup and an installed Skyrim. Run them
//! with `cargo test -p agora-cli --test game_import_mo2_real -- --ignored --nocapture`. The import
//! itself (copying about 214,592 files) is never run here: it is the user's done-test for Phase 4.

#![cfg(windows)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use agora_core::ctx::CoreContext;
use agora_core::game_discovery::{discover_all, file_version};
use agora_core::game_import::{self, Mo2Request};
use agora_core::game_registry::{identify_installs, GameRegistry, PackageSource};

const REAL_INI: &str = r"D:\Skyrim-MO2-Salvage\MO2\ModOrganizer.ini";
const REAL_PROFILE: &str = "Grounded Apocalypse";
const AGORA_BIN: &str = env!("CARGO_BIN_EXE_agora");

/// The bytes of the setup's small text files, which an import must never change: the MO2 settings,
/// and the profile's list files, settings and local INIs.
fn small_file_bytes(setup: &Path) -> BTreeMap<String, Vec<u8>> {
    let mut paths = vec![setup.join("ModOrganizer.ini")];
    let profile = setup.join("profiles").join(REAL_PROFILE);
    if let Ok(entries) = std::fs::read_dir(&profile) {
        for entry in entries.flatten() {
            if entry.path().is_file() {
                paths.push(entry.path());
            }
        }
    }
    let mut out = BTreeMap::new();
    for path in paths {
        if let Ok(bytes) = std::fs::read(&path) {
            out.insert(path.display().to_string(), bytes);
        }
    }
    out
}

#[test]
#[ignore = "reads the user's real Mod Organizer 2 setup; run with --ignored"]
fn real_setup_plan_is_read_only_and_prints_the_plan() {
    let setup = Path::new(REAL_INI).parent().unwrap().to_path_buf();
    assert!(
        Path::new(REAL_INI).is_file(),
        "the real setup is not at {REAL_INI}"
    );

    let mut builder = GameRegistry::builder();
    builder
        .add(
            PackageSource::Compiled {
                crate_name: "agora-game-creation".to_string(),
            },
            agora_game_creation::game_package(),
        )
        .expect("the Skyrim package registers");
    let registry = Arc::new(builder.build());

    let scratch = tempfile::TempDir::new().unwrap();
    let ctx = CoreContext::for_testing(scratch.path().join("app_data"));
    agora_core::db::init_local_state_db(&ctx.paths.local_state_db()).unwrap();
    let ctx = ctx.with_games(registry.clone());

    let before = small_file_bytes(&setup);
    let discovered = discover_all();
    let inventory = identify_installs(&registry, &discovered, &file_version::read_file_version);
    let request = Mo2Request {
        ini_path: PathBuf::from(REAL_INI),
        profile: REAL_PROFILE.to_string(),
        name: None,
        copy_saves: false,
    };
    let plan = game_import::plan(&ctx, &inventory, &request).expect("the real setup plans");
    let after = small_file_bytes(&setup);
    assert!(before == after, "the setup changed while it was being read");

    println!(
        "== Real MO2 plan: {} / {} ==",
        plan.profile, plan.mo2_game_name
    );
    println!(
        "install: {} at {}",
        plan.install_id,
        plan.install_location.display()
    );
    println!(
        "mods: {} enabled, {} disabled, {} files, {:.2} GB",
        plan.mods_enabled,
        plan.mods_disabled,
        plan.files,
        plan.bytes as f64 / 1e9
    );
    println!(
        "separators: {}, unmanaged: {}, problems: {}",
        plan.separators,
        plan.unmanaged.len(),
        plan.problems.len()
    );
    for problem in &plan.problems {
        println!(
            "  problem line {:?}: {}: {}",
            problem.line, problem.entry, problem.reason
        );
    }
    let with_meta = plan
        .mods
        .iter()
        .filter(|m| {
            matches!(
                m.provenance,
                agora_core::content_store::Mo2Provenance::Claimed { .. }
            )
        })
        .count();
    println!(
        "mods with a readable meta.ini: {with_meta} of {}",
        plan.mods.len()
    );
    println!(
        "overwrite: present={} {} files, {:.2} GB",
        plan.overwrite.present,
        plan.overwrite.files,
        plan.overwrite.bytes as f64 / 1e9
    );
    for generated in &plan.overwrite.generated {
        println!(
            "  generated by {} ({}): {} files, {:.2} MB (inputs unknown)",
            generated.name,
            generated.tool,
            generated.files,
            generated.bytes as f64 / 1e6
        );
        for sample in generated.sample.iter().take(5) {
            println!("    e.g. {sample}");
        }
    }
    println!(
        "  everything else -> \"MO2 overwrite\": {} files, {:.2} MB",
        plan.overwrite.rest_files,
        plan.overwrite.rest_bytes as f64 / 1e6
    );
    println!(
        "plugins: kept={} {} lines, {} active, {} locked, always-loaded left out: {:?}",
        plan.plugins.kept,
        plan.plugins.lines.len(),
        plan.plugins.active,
        plan.plugins.locked.len(),
        plan.plugins.implicit_skipped
    );
    for note in &plan.plugins.notes {
        println!("  plugin note: {note}");
    }
    println!(
        "INIs (local={}): {:?}",
        plan.local_settings,
        plan.inis.iter().map(|i| &i.name).collect::<Vec<_>>()
    );
    println!(
        "saves (local={}): {} files, {:.2} MB, from {:?}",
        plan.saves.local,
        plan.saves.files,
        plan.saves.bytes as f64 / 1e6,
        plan.saves.from
    );
    for warning in &plan.warnings {
        println!("warning: {warning}");
    }

    // The modlist has 368 mod lines (365 enabled, 3 disabled) and 27 unmanaged lines.
    assert_eq!(plan.unmanaged.len(), 27);
    assert_eq!(
        plan.mods.len() + plan.separators + plan.problems.len(),
        368,
        "every mod line is planned, skipped or reported"
    );
}

#[test]
#[ignore = "runs the CLI dry-run on the user's real Mod Organizer 2 setup; run with --ignored"]
fn real_setup_dry_run_through_the_cli() {
    let data_dir = tempfile::TempDir::new().unwrap();
    let output = Command::new(AGORA_BIN)
        .arg("--data-dir")
        .arg(data_dir.path())
        .args([
            "games",
            "import",
            "mo2",
            REAL_INI,
            "--profile",
            REAL_PROFILE,
            "--dry-run",
        ])
        .output()
        .expect("agora runs");
    let stdout = String::from_utf8_lossy(&output.stdout);
    println!("{stdout}");
    println!("{}", String::from_utf8_lossy(&output.stderr));
    assert!(output.status.success(), "the dry run failed");
    assert!(stdout.contains("Import plan"));
    assert!(stdout.contains("Nothing was stored"));
}
