#!/usr/bin/env python3
"""Convert the prototype's music-tracks.js into the app's tracks.ts module.

The 13-track dataset (~192 KB of note data) is a GENERATED artifact of
docs/interactive/prototypes/make-tracks.py + mxl2track.py. Porting it by hand
would be forking data that is already verified (every voice sums to `beats`,
opening frequencies match the score). This script performs the mechanical
`window.MUSIC_TRACKS = [...]` -> `export const MUSIC_TRACKS: MusicTrack[] =
[...]` transform and nothing else.

Usage:
    python scripts/make_ambience_tracks.py \
        docs/interactive/prototypes/music-tracks.js \
        desktop/src/features/ambience/engine/audio/tracks.ts

The voice-sum assertion that music-tracks.js throws at load time is kept as a
unit test (ambience.test.ts) so it runs in CI instead of throwing in
production.
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """/**
 * MUSIC_TRACKS - public-domain music for the Agora ambience layer.
 *
 * GENERATED FILE. Do not edit by hand: run
 * `python scripts/make_ambience_tracks.py` which transforms the verified
 * prototype dataset (docs/interactive/prototypes/music-tracks.js), itself
 * generated by make-tracks.py / mxl2track.py from real MusicXML.
 *
 * Nothing here is transcribed from memory. Every track is generated from a
 * MusicXML source; see `source` on each entry.
 *
 * Complete pieces, not loop edits - they repeat from the top the way the music
 * does. Repeats are played once through; 1st endings are skipped so a single
 * pass flows. Every voice is verified to sum to exactly `beats` (see
 * ambience.test.ts) - voices that disagree by a fraction of a beat drift
 * further apart on every repeat.
 *
 * Format: each voice is a sequential list of [pitch, beats], where pitch is a
 * note name, an array of names for a chord, or "R" for a rest. `beats` counts
 * quarter notes, and `bpm` is quarter notes per minute, so a beat lasts
 * 60 / bpm seconds. Durations are NOT on a fixed grid - triplets are 0.3333 -
 * so a player must walk each voice's list, not sample a 16th-note grid.
 *
 * LICENSING. Every composition here is public domain: Pachelbel d. 1706,
 * Beethoven d. 1827, Tchaikovsky d. 1893, Rimsky-Korsakov d. 1908, Debussy
 * d. 1918, Satie d. 1925, Grieg d. 1907, Greensleeves traditional (c. 1580).
 * Sources differ in what they declare, and that difference matters:
 *   - Moonlight is OpenScore (CC0) - an explicit public-domain dedication.
 *   - Mountain King declares rights: Public Domain.
 *   - The Gymnopedies are our own OMR of an IMSLP scan.
 *   - The rest are MuseScore community uploads with no rights statement. The
 *     NOTES are public domain, but a community upload that is a genuine
 *     ARRANGEMENT reflects the arranger's own choices (Symphony No. 5, Flight
 *     of the Bumblebee, Sugar Plum Fairy, Canon in D, Greensleeves). Fur
 *     Elise and Clair de Lune were written for piano, so those files are
 *     transcriptions of a public-domain original.
 *
 * TEMPO. Taken from each file's first tempo mark unless `tempoNote` says
 * otherwise.
 */

export type MusicMood = 'calm' | 'moody' | 'playful' | 'exciting' | 'dramatic' | 'peaceful' | 'wistful' | 'familiar' | 'bright';
export type MusicPitch = string | string[];

export interface MusicVoice {
  name: string;
  wave: OscillatorType;
  gain: number;
  seq: Array<[MusicPitch, number]>;
}

export interface MusicTrack {
  id: string;
  name: string;
  composer: string;
  year: number;
  marking: string;
  mood: MusicMood;
  bpm: number;
  beatsPerBar: number;
  bars: number;
  beats: number;
  source: string;
  instrument?: string;
  tempoNote?: string;
  voices: MusicVoice[];
}

export const MUSIC_TRACKS: MusicTrack[] = [
"""

FOOTER = """];
"""


def convert(src: Path, dst: Path) -> None:
    text = src.read_text(encoding="utf-8")
    marker = "window.MUSIC_TRACKS = ["
    start = text.find(marker)
    if start < 0:
        raise SystemExit(f"cannot find '{marker}' in {src}")
    start += len(marker)
    # The array closes with the first "];" on its own line after the start.
    close = text.find("];", start)
    if close < 0:
        raise SystemExit(f"cannot find closing '];' in {src}")
    body = text[start:close]

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER)
        out.write(body)
        out.write(FOOTER)
    print(f"wrote {dst} ({len(body)} bytes of track data)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    convert(Path(sys.argv[1]), Path(sys.argv[2]))
